version: '2'
services:
  odoo:
    image: odoo:10
    restart: always
    links:
      - db
    ports:
      - 80:8069
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
